version: "3"

services:
    sns_db:
        container_name: sns_db
        image: roadvirushn/sns_db
        build:
          context: ./db
          dockerfile: Dockerfile
        environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped
        volumes:
          - ./db/storage:/var/lib/mysql
        ports:
          - 3306:3306
        # networks:
          # - default_network

    sns_backend:
        image: roadvirushn/sns_backend
        build: 
          context: ./back-sk
          dockerfile: Dockerfile
        ports:
          - 8000:8080
        environment:
            SERVER_PORT: 8000
            SPRING_DATASOURCE_DRIVER-CLASS-NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
            SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
            SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
            SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
            SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
        restart: unless-stopped

        # depends_on:
        #   - sns_db
        # networks:
        #   - default_network

    sns_frontend:
        image: roadvirushn/sns_frontend
        build: 
          context: ./front-sk
          dockerfile: Dockerfile
        ports:
          - 80:80
        restart: unless-stopped
        # depends_on: 
        #   - sns_backend
#         networks:
#           - default_network
# networks:
#     default_network: